//@Library("jenkins-shared-library") _

pipeline{
	agent any
	stages{
        
        stage('Security scans'){
            echo 'TO DO'
        }

		stage('docker build '){

			steps{
				
				helloWorld()
			}
		
		}
			
	}

}