apiVersion: v1
kind: Service
metadata:
  name: com-bank-core-payments-iso-pain-008-001-10-service
  namespace: devops-tools
spec:
  type: NodePort
  selector:
    app: com-bank-core-payments-iso-pain-008-001-10
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30100
    name: http